### ISSUE TITLE
Interface Switching Not Working (Only eth0 Captures)

### ISSUE THREAD

**Issue by x9xhack** [Chleba/netscanner#47]
**Description**: When using the f key to switch interfaces, the app only captures packets from eth0. Selecting other interfaces has no effect.

Steps to Reproduce:

Press f to change the network interface.
Select a different interface (e.g., tun0).
Capture continues on eth0.

**Expected Behavior**: Packet capture should work on the selected interface.

**Actual Behavior**: Only eth0 captures packets, other interfaces are ignored.

OS: kali-rolling 2025-1
Version: netscanner v0.6.2-

**Comment by Chleba** [comment]
btw. @x9xhack please what exact version of `netscanner` you using ?

**Comment by x9xhack** [comment]
Thank you for your swift action.

netscanner v0.6.2-

**Comment by Chleba** [comment]
Hi,
I fixed it here: https://github.com/Chleba/netscanner/commit/f364a8e4ced36034b93b0e07121bb62c6c02e8f8.
Please check if it's working for you and let me know. I will close this issue but feel free to open it if there is any issue with this fix.
Thanks.

**Comment by x9xhack** [comment]
Hi @Chleba,

Thank you for the fix.

It still doesn't work for me. Am I doing something wrong?

![Image](https://github.com/user-attachments/assets/b24f200b-1e8d-4627-a124-e6326ba5f580)

**Comment by Chleba** [comment]
Hi @x9xhack,

Could you give me more details please ? What OS ? Is the packets from `eth0` stop when you switch your interface (that should definitely happen).  Is the second interface some virtual interface ? Just more details please.

**Comment by x9xhack** [comment]
Hi

OS: Kali Rolling 2025-1, running in a VM with VMware. 
tun0 is the OpenVPN virtual interface.

**Comment by Chleba** [comment]
Hi @x9xhack,
Please tell me if packet dump logs will stop from `eth0` when you switch interface to `tun0`.
Also is there some traffic from `tun0` interface ?

**Comment by x9xhack** [comment]
Hi @Chleba 

1 - Yes, packet dumps stop for eth0 when switching interface to tun0
2 - Yes , there is traffic for tun0. ( tested with curl , ping , nmap port scan )
